import Head from 'next/head'
import { ReactNode } from 'react'
import { FaSave } from 'react-icons/fa'

import { Footer } from '@/src/components/layout/Footer'
import { Nav } from '@/src/components/layout/Nav'
import { useUiState } from '@/src/providers/UiStateProvider'

interface LayoutProps {
  children: ReactNode
}

export default function Layout({ children }: LayoutProps) {
  const { shouldShowLoadingIndicator } = useUiState()

  return (
    <>
      <Head>
        <title>Portion Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={'tw-absolute tw-inset-0 tw-h-full tw-flex tw-flex-col'}>
        <Nav />
        <main className={'tw-flex-1'}>{children}</main>
        {shouldShowLoadingIndicator && (
          <FaSave className={'tw-fixed tw-left-4 tw-bottom-4'} size={20} />
        )}
        <Footer />
      </div>
    </>
  )
}
