import Head from 'next/head'
import { ReactNode } from 'react'

import { Footer } from '@/src/components/Footer'
import { Nav } from '@/src/components/Nav'

interface LayoutProps {
  children: ReactNode
}

export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Portion Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={'tw-absolute tw-inset-0 tw-h-full tw-flex tw-flex-col'}>
        <Nav />
        <main className={'tw-flex-1'}>{children}</main>
        <Footer />
      </div>
    </>
  )
}
